/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Datos.DAlmacen;
import Datos.DDetalleRecibos;
import Datos.DRecibos;
import Logica.LAlmacen;
import Logica.LDetalleRecibos;
import Logica.LRecibos;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joset
 */
public class FrmRecibos extends javax.swing.JInternalFrame {
    
    DefaultTableModel miModelo;
    /**
     * Creates new form FrmRecibos
     */
    public FrmRecibos() {
        initComponents();
        habilitar(true);
        
        txtTotal.setEditable(false);
        lblPersonaE.setVisible(false);
        miModelo = (DefaultTableModel) tblRecibos.getModel();

        tblRecibos.getColumn("CÓDIGO").setWidth(15);
        tblRecibos.getColumn("CÓDIGO").setPreferredWidth(15);

        tblRecibos.getColumn("DESCRIPCIÓN").setWidth(220);
        tblRecibos.getColumn("DESCRIPCIÓN").setPreferredWidth(220);

        tblRecibos.getColumn("CANTIDAD").setWidth(20);
        tblRecibos.getColumn("CANTIDAD").setPreferredWidth(20);

        tblRecibos.getColumn("U/MEDIDA").setWidth(20);
        tblRecibos.getColumn("U/MEDIDA").setPreferredWidth(20);

        tblRecibos.getColumn("P/UNITARIO").setWidth(20);
        tblRecibos.getColumn("P/UNITARIO").setPreferredWidth(20);

        tblRecibos.getColumn("TOTAL").setWidth(20);
        tblRecibos.getColumn("TOTAL").setPreferredWidth(20);
        
        tblRecibos.getColumn("LÍNEA").setWidth(20);
        tblRecibos.getColumn("LÍNEA").setPreferredWidth(20);

        
        ImageIcon imNuevo = new ImageIcon(getClass().getClassLoader().getResource("Imagenes/iconSuma.png"));
        Icon icNuevo = new ImageIcon(imNuevo.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH));
        btnNuevo.setIcon(icNuevo);

        ImageIcon imGuardar = new ImageIcon(getClass().getClassLoader().getResource("Imagenes/iconGuardar.png"));
        Icon icGuardar = new ImageIcon(imGuardar.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH));
        btnGuardar.setIcon(icGuardar);

        ImageIcon imCancelar = new ImageIcon(getClass().getClassLoader().getResource("Imagenes/iconCancelar.png"));
        Icon icCancelar = new ImageIcon(imCancelar.getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH));
        btnCancelar.setIcon(icCancelar);
        
    }
    
    public void habilitar(boolean b) {

        txtBuscar.setEnabled(!b);
        txtFecha.setEnabled(!b);
        btnCancelar.setEnabled(!b);
        btnGuardar.setEnabled(!b);
        btnNuevo.setEnabled(b);
        txtRecibe.setEnabled(!b);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecibos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRecibe = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPersonaE = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Recibos");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tblRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIPCIÓN", "CANTIDAD", "P/UNITARIO", "U/MEDIDA", "LÍNEA", "TOTAL", "IdLinea"
            }
        ));
        tblRecibos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblRecibosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecibos);
        if (tblRecibos.getColumnModel().getColumnCount() > 0) {
            tblRecibos.getColumnModel().getColumn(7).setMinWidth(0);
            tblRecibos.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblRecibos.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha:");

        txtRecibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecibeActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jLabel2.setText("Receptor:");

        jLabel3.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(lblPersonaE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonaE, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(66, 66, 66)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String msgfinal = "";

        if (txtRecibe.getText().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Campo receptor obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtRecibe.requestFocusInWindow();
            return;
        }

        if (txtFecha.getDate() == null) {

            JOptionPane.showMessageDialog(rootPane, "Campo fecha obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocusInWindow();
            return;
        }

        LRecibos fn = new LRecibos();
        DRecibos dts = new DRecibos();

        Calendar cal;

        cal = txtFecha.getCalendar();

        int aa, mm, dd;

        aa = cal.get(Calendar.YEAR) - 1900;
        mm = cal.get(Calendar.MONTH);
        dd = cal.get(Calendar.DAY_OF_MONTH);

        dts.setFechaRecibo(new Date(aa, mm, dd));
        dts.setPersonaEntrega(lblPersonaE.getText());
        dts.setPersonaRecibe(txtRecibe.getText());

        int idrec = fn.insertarRecibos(dts);
        if (idrec > 0){
            
            int filas = tblRecibos.getRowCount();
            for (int i = 0; i < filas; i++) {
                
                String idprod = tblRecibos.getValueAt(i,0).toString();
                int idlinea = Integer.parseInt(tblRecibos.getValueAt(i, 7).toString());
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double total = Double.parseDouble(tblRecibos.getValueAt(i, 6).toString());
                
                LDetalleRecibos fundf = new LDetalleRecibos();
                DDetalleRecibos dtsf = new DDetalleRecibos();
                dtsf.setRecibosId(idrec);
                dtsf.setProductosId(idprod);
                dtsf.setLineasId(idlinea);
                dtsf.setCantidad(cantidad);
                dtsf.setTotal(total);
                String mensaje = fundf.registrarDetalleRecibos(dtsf);
                
                if(mensaje.equals("si")){
                    LAlmacen funAl = new LAlmacen();
                    DAlmacen dtsp = new DAlmacen ();

                    dtsp.setIdAlmacen(idprod);
                    dtsp.setStock(cantidad);

                    msgfinal = funAl.disminuirStock(dtsp);
                }

            }

            JOptionPane.showMessageDialog(rootPane, msgfinal , "Información", JOptionPane.INFORMATION_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(rootPane, "Ocurrió un problema al insertar", "Información", JOptionPane.ERROR_MESSAGE);

        }
        habilitar(true);
        limpiar();
                
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void limpiar(){
        
        txtRecibe.setText("");
        txtFecha.setDate(null);
        txtBuscar.setText("");
        txtTotal.setText("");
        
        try{
            DefaultTableModel modelo = (DefaultTableModel) tblRecibos.getModel();
            int filas = tblRecibos.getRowCount();
            for(int i = 0; filas > i; i++){
                
                modelo.removeRow(0);
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean b = estaenTabla(txtBuscar.getText());
            if (b == false) {
                mostrarProductos(txtBuscar.getText());
            }
            sumarTotal();
            txtBuscar.setText("");
        }
     
        
        
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void tblRecibosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRecibosKeyPressed
        // TODO add your handling code here:
        DecimalFormat ft = new DecimalFormat("####.00");

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            for (int i = 0; i < tblRecibos.getRowCount(); i++) {
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double preciounitario = Double.parseDouble(tblRecibos.getValueAt(i, 3).toString());

                double totalparcial = cantidad * preciounitario;
                tblRecibos.setValueAt(ft.format(totalparcial), i, 6);
            }
            sumarTotal();
        }
        
    }//GEN-LAST:event_tblRecibosKeyPressed

    private void txtRecibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecibeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecibeActionPerformed

    public boolean estaenTabla(String texto) {

        boolean res = false;
        DecimalFormat ft = new DecimalFormat("####.00");
        for (int i = 0; i < tblRecibos.getRowCount(); i++) {

            String codigo = tblRecibos.getValueAt(i, 0).toString();
            if (codigo.equals(texto)) {
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double preciounitario = Double.parseDouble(tblRecibos.getValueAt(i, 3).toString());
                int totalcantidad = cantidad + 1;
                tblRecibos.setValueAt(totalcantidad, i, 2);

                double totalparcial = totalcantidad * preciounitario;
                tblRecibos.setValueAt(ft.format(totalparcial), i, 6);
                res = true;
            }

        }
        sumarTotal();
        return res;
    }
    
    public void sumarTotal() {

        DecimalFormat ft = new DecimalFormat("####.00");
        double totalparcial = 0, totalfinal = 0;
        for (int i = 0; i < tblRecibos.getRowCount(); i++) {

            totalparcial = Double.parseDouble(tblRecibos.getValueAt(i, 6).toString());
            totalfinal += totalparcial;
            txtTotal.setText(ft.format(totalfinal));
        }

    }
    
    public void mostrarProductos(String  producto) {

        LAlmacen fn = new LAlmacen();
        DAlmacen dts = new DAlmacen();
        DefaultTableModel tblDatos = (DefaultTableModel) tblRecibos.getModel();
        dts.setIdAlmacen(producto);
        String registros[] = fn.mostrarbuscarProductosRec(dts);
        if (registros[0] != null) {

            tblDatos.insertRow(0, registros);
            tblRecibos.setModel(tblDatos);

        } else {

         JOptionPane.showMessageDialog(rootPane, "Producto no existe en el inventario, favor de validar.");

        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPersonaE;
    private javax.swing.JTable tblRecibos;
    private javax.swing.JTextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtRecibe;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public void setUsuario(String personae) {
        
        lblPersonaE.setText(personae);
        
    }
}
